[build]
  command = "npm install --force && npm run build"
  publish = "dist"
  site_id = "d948ea23-b9c9-4f19-b06c-8e490dd53c91"

[build.environment]
  NODE_VERSION = "18"
  CI = "false"
  NETLIFY_SITE_NAME = "resilient-frangipane-0c6441"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "frame-ancestors 'none';"
